on: 

 workflow_dispatch:
jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Get Pokemon name
        uses: philschmid/blog-custom-github-action@master
        id: pokemon
        with:
          pokemon_id: ''
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
      - name: Validate Template via bash commands
        id: validate
        shell: bash
        run: |
          if [ -z ${{ steps.pokemon.outputs.pokemon_name }} ] || [ ${{ steps.pokemon.outputs.pokemon_name }} == "null" ]; 
          then
            echo "change request id is false"
            echo "::set-output name=result::failure"
          else
             echo "change request id is true"
             echo "::set-output name=result::success"
      
          fi
      - name: commsn
        id: build
        run: |
            exit 1
            echo ::set-output name=exit_code::$?
            echo "Exited with $?"
      - name: Deployment Successful
        if: ${{ steps.validate.outputs.result == 'success' && steps.build.outputs.exit_code == 0 }}
        run: echo "devl deploy"
      - name: Deployment Failure
        if: ${{ steps.validate.outputs.result == 'failure' &&  steps.build.outputs.exit_code != 0 }}
        run: echo "prod deploy"

