on: 

 workflow_dispatch:
jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Get Pokemon name
        uses: philschmid/blog-custom-github-action@master
        id: pokemon
        with:
          pokemon_id: ''
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
      - name: Validate Template via bash commands
        id: validate
        shell: bash
        run: |
          echo  ${{ steps.pokemon.outputs.pokemon_name }} 
          if [[ -z "${{ steps.pokemon.outputs.pokemon_name }}" || "${{ steps.pokemon.outputs.pokemon_name }}" -eq "null" ]]; 
          then
            echo ${{ steps.pokemon.outputs.pokemon_name }} 
            echo "::set-output name=result::failure"
          else
            echo ${{ steps.pokemon.outputs.pokemon_name }} 
            echo "::set-output name=result::success"
          fi
      - name: commsn
        run: ls 
      - name: Deployment Successful
        if:  ${{ steps.validate.outputs.result == 'success' && success() }}
        run: echo "devl deploy"
      - name: Deployment Failure
        if:  ${{ steps.validate.outputs.result == 'failure' && failure() }}
        run: echo "prod deploy"

